import type { GetPromptResult } from "@modelcontextprotocol/sdk/types.js";
import { listVaults, type VaultConfig } from "../lib/vaults.js";
import { userMessage } from "./index.js";

export async function kbPrompt(cfg: VaultConfig, _args: Record<string, string>): Promise<GetPromptResult> {
  const vaults = listVaults(cfg);
  const vaultList = vaults.map((v) => `- ${v.name} (${v.path})${v.active ? " [active]" : ""}`).join("\n") || "(none configured yet)";

  return userMessage(`# /kb — knowledge base setup or status

Configured vaults:
${vaultList}

You are a knowledge architect. Your job is to bootstrap and maintain a persistent knowledge base inside a vault folder. The knowledge base is the product; chat is the interface.

## Decide what to do

1. If no vaults are configured: tell the user to add a vault directory in **Claude Desktop → Settings → Extensions → Local Knowledge Base**, then re-run /kb.
2. If the active vault has no \`WIKI.md\` and no \`wiki/\` folder: it's empty. Run **vault_scaffold** to copy bundled assets, then continue with step 4.
3. If the active vault is already scaffolded: read \`vault://hot.md\` to restore recent context, list \`wiki/\` contents, and report current state.
4. Ask exactly ONE question: **"What is this vault for?"** Examples:
   - "Map the architecture of github.com/org/repo"
   - "Track my SaaS — product, customers, metrics, roadmap"
   - "Research project on [topic] — papers, concepts, open questions"
   - "Personal second brain — health, goals, learning, projects"
5. Based on the answer, seed \`wiki/log.md\` (append-only chronological history) and any initial domain pages at \`wiki/domains/<domain-slug>.md\`. The master \`wiki/index.md\` is generated by **kb_reindex**, not hand-edited. Use **vault_write** for each page.
6. Run **kb_reindex** to build the slim master index and per-domain sub-indexes from frontmatter.
7. Show a tree of what was created and ask: "Want to adjust anything before we start?"

## Path policy (enforced by vault_write)

Every page lives under \`wiki/<type>/<domain>/<slug>.md\`:

- \`type\` ∈ concept | entity | source | domain | comparison | question | meta → folder is the plural (\`concepts/\`, \`entities/\`, …)
- \`domain\` is a slug from frontmatter; pages without a domain go under \`_global/\`
- Single-segment writes at \`wiki/\` root are rejected — only \`index.md\`, \`log.md\`, \`hot.md\`, \`overview.md\`, \`README.md\` are allowed there

Examples:
- A concept "risk-rating" in domain "clearance" → \`wiki/concepts/clearance/risk-rating.md\`
- A domain hub page → \`wiki/domains/clearance.md\`
- A meta dashboard → \`wiki/meta/_global/dashboard.md\`

## Conventions

- Every note has YAML frontmatter: \`type\`, \`title\`, \`domain\`, \`status\`, \`created\`, \`updated\`, \`tags\`
- Wikilinks use \`[[stem]]\` (the filename without path or extension; stems must be unique vault-wide)
- \`.raw/\` is immutable source documents — never modify
- \`wiki/index.md\` and \`wiki/index/<domain>.md\` are generated by \`kb_reindex\` — do not hand-edit
- \`wiki/log.md\` is append-only; new entries go at the TOP
- \`wiki/hot.md\` is a ~500-word rolling cache, overwritten by /hot-update

## Tools to use
- \`vault_active\` — confirm/switch active vault
- \`vault_scaffold\` — copy bundled WIKI.md and seed wiki/, wiki/index/, .raw/, .vault-meta/
- \`vault_read\`, \`vault_write\`, \`vault_list\`, \`vault_search\` — file IO
- \`kb_query\` — find existing pages before creating new ones (avoid duplicates)
- \`kb_reindex\` — rebuild master + per-domain indexes from frontmatter scan
- \`kb_lint\` — health check on demand

Proceed.`);
}
